# Create a Docker image that is ready to run UniMath

# Use Ubuntu LTS version.
FROM ubuntu:xenial
MAINTAINER Karl Palmskog <palmskog@gmail.com>

# According to
# https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/:
#  * Put "apt-get update" and "apt-get install" in the same RUN command.
#  * Do not run "apt-get upgrade"; instead get upstream to update.
RUN apt-get -qqy update \
&& apt-get -qqy install \
  software-properties-common \
  git \
  make \
  m4 \
  aspcud \
  ocaml \
  opam \
  time \
  libgtk2.0-dev \
  libgtksourceview2.0-dev \
  emacs \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* \
&& opam init --compiler=4.06.0 --yes --no-setup \
&& eval $(opam config env) \
&& echo '. /root/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true' >> ~/.profile \
&& opam install lablgtk camlp5 num \
